# Generated by Django 4.2.11 on 2024-04-19 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
